name: Hello World

on: [push]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Print message
        run: echo "Hello GitHub Actions!"
      - name: Print message 2
        run: echo "Hello User "
      - name: Print mesg like step 3
        run: echo "clear gaurav query"
