name: Hello World

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello $name"
      - name: Print message 2
        run: echo "Your designation is $desig "
      - name: Print mesg like step 3
        run: echo "You are going to join at $company"
          
