
name: Deploy file from another repo via SSH key

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo A (current repo)
        uses: actions/checkout@v3
        
      - name: Checkout Repo B (private)
        uses: actions/checkout@v3
        with:
          repository: triovative-bot/daypredict
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: main          # 👈 force main branch
          path: repo-b
          persist-credentials: false
          ssh-strict: false   # avoid known_hosts issues

      - name: Debug (list files from Repo B)
        run: ls -R repo-b

      - name: Copy file from Repo B to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # server SSH key
          port: 22
          source: "repo-b/index.php"
          target: "/data"
          overwrite: true
