name: Deploy file from Repo B to server

on:
  workflow_dispatch:
    inputs:
      server:
        description: "Target server hostname or IP"
        required: true
      user:
        description: "SSH username for target server"
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo A (current repo)
        uses: actions/checkout@v3

      - name: Checkout Repo B using SSH key
        uses: actions/checkout@v3
        with:
          repository: triovative-bot/daypredict     # 👈 change this
          ssh-key: ${{ secrets.REPO_B_SSH_KEY }}
          path: repo-b

      - name: Debug (list files from Repo B)
        run: ls -R repo-b

      - name: Transfer file to target server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ github.event.inputs.server }}   # 👈 runtime input
          username: ${{ github.event.inputs.user }} # 👈 runtime input
          key: ${{ secrets.SSH_PRIVATE_KEY }}               # private key for server
          port: 22
          source: "./index.php"     # 👈 adjust file path
          target: "/data"
          overwrite: true
